Задание 10.5

Получите сумму чисел, сохранённых в переменных a и b.

In [3]:
#from hidden import a, b
# Пишите здесь команды, который помогут
# найти ответы на вопросы
a, b = 2147483548, 2147471336
print(a, b)


import numpy as np

a = np.int64(a)
b = np.int64(b)

print(a+b)

2147483548 2147471336
4294954884


ЗАДАНИЕ 10.6 (ВЫПОЛНЯЕТСЯ В CODEBOARD НИЖЕ)

Напишите функцию get_chess, которая принимает на вход длину стороны квадрата a и возвращает двумерный массив формы (a, a), заполненный 0 и 1 в шахматном порядке. В левом верхнем углу всегда должен быть ноль.

Примечание: воспользуйтесь функцией zeros из библиотеки numpy, а затем с помощью срезов без циклов задайте необходимым элементам значение 1.

Напоминание: в Python для получения каждого второго элемента используется срез [::2]. Подумайте, как грамотно применить этот принцип к двумерному массиву.

In [4]:
import numpy as np
def get_chess(a):
    arr = np.zeros((a, a))
    arr[1::2, ::2] = 1
    arr[::2, 1::2] = 1
    return arr

get_chess(3)

array([[0., 1., 0.],
       [1., 0., 1.],
       [0., 1., 0.]])

ЗАДАНИЕ 10.7 (ВЫПОЛНЯЕТСЯ В CODEBOARD НИЖЕ)


Вы разрабатываете приложение для прослушивания музыки. Конечно же, там будет доступна функция перемешивания плейлиста. Пользователю может настолько понравиться перемешанная версия плейлиста, что он захочет сохранить его копию. Однако вы не хотите хранить в памяти новую версию плейлиста, а просто хотите сохранять тот seed, с которым он был сгенерирован.

Для этого напишите функцию shuffle_seed(<array>),  которая принимает на вход массив из чисел, генерирует случайное число для seed в диапазоне от 0 до 2**32 - 1 (включительно) и возвращает кортеж: перемешанный с данным seed массив (исходный массив должен оставаться без изменений), а также seed, с которым этот массив был получен.

In [5]:
import numpy as np
def shuffle_seed(array):
    seed = np.random.randint((2**32), dtype=np.int64)
    np.random.seed(seed)
    result = np.random.permutation(array)
    return result, seed   

array = [1, 2, 3, 4, 5]
shuffle_seed(array)

(array([3, 4, 2, 5, 1]), 618764691)

ЗАДАНИЕ 10.8 (ВЫПОЛНЯЕТСЯ В CODEBOARD НИЖЕ)

Напишите функцию min_max_dist, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.

In [6]:
import numpy as np

def min_max_dist(*vectors):
    dists = list()
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            dists.append(np.linalg.norm(vectors[i] - vectors[j]))
    return (min(dists), max(dists))

vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

min_max_dist(vec1, vec2, vec3)

(5.196152422706632, 10.392304845413264)

ЗАДАНИЕ 10.9 (ВЫПОЛНЯЕТСЯ В CODEBOARD НИЖЕ)

Напишите функцию any_normal, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает True, если есть хотя бы одна пара перпендикулярных векторов. Иначе возвращает False.

In [7]:
import numpy as np

def any_normal(*vectors):
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            if np.dot(vectors[i], vectors[j]) == 0:
                return True
    return False

vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])
print(any_normal(vec1, vec2, vec3))

True


ЗАДАНИЕ 10.10 (ВЫПОЛНЯЕТСЯ В CODEBOARD НИЖЕ)


Напишите функцию get_loto(num), генерирующую трёхмерный массив случайных целых чисел от 1 до 100 (включительно). Это поля для игры в лото.

Трёхмерный массив должен состоять из таблиц чисел формы 5х5, то есть итоговая форма — (num, 5, 5).

Функция возвращает полученный массив.

In [8]:
import numpy as np

def get_loto(num):
    loto = np.random.randint(1, 101, size=(num, 5, 5))
    return loto

get_loto(3)

array([[[  6,  25,  75,  64,  95],
        [  2,  42,  55,  15,  55],
        [  6,  97,  54,  87,  56],
        [  5,  91,  38,  44,   9],
        [ 29, 100,   9,  68,  95]],

       [[ 40,  38,  63,   6,  37],
        [ 82,  26,  39,  57,  76],
        [ 26,   3,  53,  11,  34],
        [ 88,  72,  83,  84,  44],
        [ 69,  87,  18,  37,  60]],

       [[ 69,  82,  63,  93,  52],
        [  4,  66,  83,  81,  68],
        [ 98,  21,  73,   3,  52],
        [ 21,  13,  14,  84,  11],
        [ 49,  68,  86,  79,  24]]])

ЗАДАНИЕ 10.11 (ВЫПОЛНЯЕТСЯ В CODEBOARD НИЖЕ)

Напишите функцию get_unique_loto(num). Она так же, как и функция в задании 10.10, генерирует num полей для игры в лото, однако теперь на каждом поле 5х5 числа не могут повторяться.

Функция также должна возвращать массив формы num x 5 x 5.

In [9]:
import numpy as np
def get_unique_loto(num):
    sample = np.arange(1, 101)
    res = list()
    for i in range(num):
        res.append(np.random.choice(sample, replace=False, size=(5, 5)))
    res = np.array(res)
    return res

get_unique_loto(3)

array([[[44, 83, 27, 35, 89],
        [11, 66, 95, 50, 56],
        [59, 55, 47,  6, 58],
        [69, 71, 28, 38, 43],
        [91, 45, 41, 84,  5]],

       [[90,  9, 70, 40, 67],
        [50, 79, 20, 81, 48],
        [30, 74, 54, 99, 26],
        [15, 43, 27, 32, 10],
        [88, 45, 86, 58, 66]],

       [[10, 35, 38, 94, 96],
        [70, 75, 82, 58,  7],
        [28, 46, 62, 85, 57],
        [77, 74, 73, 97, 95],
        [89, 22, 13, 27, 61]]])