In [1]:
import numpy as np

In [12]:
(2**16)/2-1 #max number

32767.0

In [11]:
-(2**16)/2 #min number

-32768.0

In [26]:
import numpy as np
a = np.int8(25)
print(a)
print(type(a))

z = int(25)
print(z)
print(type(z))


25
<class 'numpy.int8'>
25
<class 'int'>


In [19]:
np.iinfo(np.int8)

iinfo(min=-32768, max=32767, dtype=int16)

In [20]:
np.iinfo(np.int16)

iinfo(min=-32768, max=32767, dtype=int16)

In [21]:
np.iinfo(a)

iinfo(min=-128, max=127, dtype=int8)

In [22]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [31]:
b = np.uint8(124)
print(b)
print(type(b))
np.iinfo(b)

124
<class 'numpy.uint8'>


iinfo(min=0, max=255, dtype=uint8)

In [32]:
a = np.int32(1000)
print(a)
# 1000
print(type(a))
# <class 'numpy.int32'>
a = 2056
print(a)
# 2056
print(type(a))
# <class 'int'>

1000
<class 'numpy.int32'>
2056
<class 'int'>


In [33]:
a = np.int32(1000)
print(a)
# 1000
print(type(a))
# <class 'numpy.int32'>
a = np.int32(2056)
print(a)
# 2056
print(type(a))
# <class 'numpy.int32'>

1000
<class 'numpy.int32'>
2056
<class 'numpy.int32'>


In [37]:
a = np.int32(1000)
b = a + 25
print(b)
print(type(b))

1025
<class 'numpy.int32'>


In [39]:
a = np.int16(1000)
b = np.int8(25)
c = a + b
print(c)
# 1025
print(type(c))
# <class 'numpy.int32'>

1025
<class 'numpy.int16'>


In [43]:
a = np.int8(260)
print(a)
np.iinfo(a)

4


iinfo(min=-128, max=127, dtype=int8)

In [50]:
a = np.int32(2147483610)
b = np.int32(2147483605)
print(a, b)
# 2147483610 2147483605
np.iinfo(a)
np.iinfo(b)
print(a + b)
# -81
# RuntimeWarning: overflow encountered in int_scalars
# Переполнено int'овое значение

2147483610 2147483605
-81


C:\Users\Dmitriy\AppData\Local\Temp\ipykernel_12840\3684962798.py:7: RuntimeWarning: overflow encountered in long_scalars
  print(a + b)


In [51]:
a = np.int32(2147483610)

np.iinfo(a)


iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [53]:
a = np.int32(2147483610)
b = np.int32(2147483605)
print(a, b)
# 2147483610 2147483605
print(np.int64(a) + np.int64(b))
# 4294967215

2147483610 2147483605
4294967215


In [56]:
np.finfo(np.float16)

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

In [57]:
np.finfo(np.float32)

finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)

In [58]:
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [62]:
#np.finfo(np.float128)

In [63]:
print(np.float16(4.12))
# 4.12
print(np.float16(4.13))
# 4.13
print(np.float16(4.123))
# 4.12
print(np.float16(4.124))
# 4.125
print(np.float16(4.125))
# 4.125

4.12
4.13
4.12
4.125
4.125


In [64]:
print(np.sctypeDict)
print(len(np.sctypeDict))
# 158, но может быть 135 или 139

{'?': <class 'numpy.bool_'>, 0: <class 'numpy.bool_'>, 'byte': <class 'numpy.int8'>, 'b': <class 'numpy.int8'>, 1: <class 'numpy.int8'>, 'ubyte': <class 'numpy.uint8'>, 'B': <class 'numpy.uint8'>, 2: <class 'numpy.uint8'>, 'short': <class 'numpy.int16'>, 'h': <class 'numpy.int16'>, 3: <class 'numpy.int16'>, 'ushort': <class 'numpy.uint16'>, 'H': <class 'numpy.uint16'>, 4: <class 'numpy.uint16'>, 'i': <class 'numpy.intc'>, 5: <class 'numpy.intc'>, 'uint': <class 'numpy.uint32'>, 'I': <class 'numpy.uintc'>, 6: <class 'numpy.uintc'>, 'intp': <class 'numpy.int64'>, 'p': <class 'numpy.int64'>, 9: <class 'numpy.int64'>, 'uintp': <class 'numpy.uint64'>, 'P': <class 'numpy.uint64'>, 10: <class 'numpy.uint64'>, 'long': <class 'numpy.int32'>, 'l': <class 'numpy.int32'>, 7: <class 'numpy.int32'>, 'L': <class 'numpy.uint32'>, 8: <class 'numpy.uint32'>, 'longlong': <class 'numpy.int64'>, 'q': <class 'numpy.int64'>, 'ulonglong': <class 'numpy.uint64'>, 'Q': <class 'numpy.uint64'>, 'half': <class 'nu

In [65]:
print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n')

<class 'numpy.bool_'>
<class 'numpy.bytes_'>
<class 'numpy.clongdouble'>
<class 'numpy.complex128'>
<class 'numpy.complex64'>
<class 'numpy.datetime64'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.intc'>
<class 'numpy.longdouble'>
<class 'numpy.object_'>
<class 'numpy.str_'>
<class 'numpy.timedelta64'>
<class 'numpy.uint16'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.uint8'>
<class 'numpy.uintc'>
<class 'numpy.void'>


In [66]:
a = True
print(type(a))
# <class 'bool'>
a = np.bool(a)
print(type(a))
# <class 'bool'>
a = np.bool_(a)
print(type(a))
# <class 'numpy.bool_'>
 
# Значения равны
print(np.bool(True) == np.bool_(True))
# True
# А типы — нет:
print(type(np.bool(True)) == type(np.bool_(True)))
# False

<class 'bool'>
<class 'bool'>
<class 'numpy.bool_'>
True
False


C:\Users\Dmitriy\AppData\Local\Temp\ipykernel_12840\1122834797.py:4: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.bool(a)
C:\Users\Dmitriy\AppData\Local\Temp\ipykernel_12840\1122834797.py:12: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(np.bool(True) == np.bool_(True))
C:\Users\Dmitriy\AppData\Local\Temp\ipykernel_12840\1122834797.py

In [67]:
a = "Hello world!"
print(type(a))
# <class 'str'>
a = np.str(a)
print(type(a))
# <class 'str'>
a = np.str_(a)
print(type(a))
# <class 'numpy.str_'>

<class 'str'>
<class 'str'>
<class 'numpy.str_'>


C:\Users\Dmitriy\AppData\Local\Temp\ipykernel_12840\985064762.py:4: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.str(a)


In [72]:
a = np.uint8(-456)
print(a)


56


6. Модуль NumPy. Массивы

In [73]:
import numpy as np
arr  = np.array([1,5,2,9,10])
arr

array([ 1,  5,  2,  9, 10])

In [74]:
print(type(arr))
#Название ndarray — это сокращение от n-dimensional array, -мерный массив.

<class 'numpy.ndarray'>


In [89]:
nd_arr = np.array([
    [12, 45, 78],
    [34, 56, 13],
    [12, 78, 76]
    ])
nd_arr

array([[12, 45, 78],
       [34, 56, 13],
       [12, 78, 76]])

In [90]:
arr.dtype

dtype('int32')

In [91]:
arr = np.array([1, 5, 2, 9, 10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [92]:
arr[2] = 2000
arr

array([  1,   5, -48,   9,  10], dtype=int8)

In [93]:
arr[2] = 125.5
arr

array([  1,   5, 125,   9,  10], dtype=int8)

In [94]:
arr[2] = '12'
arr

array([ 1,  5, 12,  9, 10], dtype=int8)

In [7]:
#arr[2] = 'test'
#arr

In [100]:
arr = np.float64(arr)
arr

array([ 1.,  5., 12.,  9., 10.])

In [102]:
arr = np.array([12321, -1234, 3435, -214, 100], dtype=np.int32)
arr

array([ 33,  46, 107,  42, 100], dtype=uint8)

In [103]:
arr = np.uint8(arr)
arr

array([ 33,  46, 107,  42, 100], dtype=uint8)

Задание 6.3

Выберите все типы данных, которые подходят для хранения в одном массиве без потери точности всех следующих чисел: 345234, 876362.12, 0, -1000, 99999999.

In [115]:
arr = np.array([345234, 876362.12, 0, -1000, 99999999], dtype=np.float64)
arr

array([ 3.4523400e+05,  8.7636212e+05,  0.0000000e+00, -1.0000000e+03,
        9.9999999e+07])

In [116]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

In [120]:
arr.ndim


1

In [119]:
nd_arr.ndim

2

In [121]:
arr.size

5

In [122]:
nd_arr.size

9

In [123]:
arr.shape

(5,)

In [124]:
nd_arr.shape

(3, 3)

In [125]:
arr.itemsize

1

In [126]:
nd_arr.itemsize

2

ЗАПОЛНЕНИЕ НОВЫХ МАССИВОВ

In [128]:
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [130]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
zeros_3d
print(zeros_3d.shape)

(5, 4, 3)


In [133]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [134]:
np.arange(2.5, 5)

array([2.5, 3.5, 4.5])

In [135]:
np.arange(2.5, 5, 0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [136]:
np.arange(2.5, 5, 0.5, dtype=np.float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

In [138]:
arr = np.linspace(1,2,10)
arr

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [141]:
arr = np.linspace(1, 2, 10, endpoint=False)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [146]:
arr,step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)

0.1111111111111111


In [148]:
arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)

0.1


Задание 6.6

С каким шагом сгенерируется массив из 60 чисел от -6 до 21 включительно? Ответ округлите до двух знаков после точки.

In [159]:
arr = np.linspace(-6, 21, 60, endpoint=True, retstep=True)
print(step)
print(step.round(2))

0.4576271186440678
0.46


Задание 6.7

С каким шагом сгенерируется массив из 60 чисел от -6 (включительно) до 21 (не включительно)? Ответ округлите до 2 знаков после точки.

In [161]:
arr = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(step)
print(step.round(2))
# 0.45


0.4576271186440678
0.46


Задание 6.8

Узнайте размерность массива mystery.

In [169]:
#print(mystery.ndim)

Задание 6.9

Какова максимальная протяжённость по одной из осей массива?

In [170]:
#print(max(mystery.shape))

Задание 6.10

Узнайте число элементов массива.

In [171]:
#print(mystery.size)

Задание 6.11

Какой тип данных у элементов массива?

In [172]:
#print(mystery.dtype)

Задание 6.12

Узнайте вес всех элементов в массиве в байтах.

In [ ]:
#print(mystery.itemsize * mystery.size)

7. Модуль NumPy. Действия с массивами

ДЕЙСТВИЯ С МАССИВАМИ

ИЗМЕНЕНИЕ ФОРМЫ МАССИВА

In [1]:
import numpy as np
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [2]:
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [10]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [11]:
arr = np.arange(8)
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
arr_trans = arr.transpose()
arr_trans

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [17]:
arr = np.arange(3)
print(arr.shape)

arr_trans = arr.transpose()
print(arr_trans.shape)

(3,)
(3,)


ИНДЕКСЫ И СРЕЗЫ В МАССИВАХ

In [19]:
arr = np.linspace(1, 2, 6)
arr

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [20]:
print(arr[2])

1.4


In [21]:
print(arr[2:4])

[1.4 1.6]


In [23]:
print(arr[::-1])

[2.  1.8 1.6 1.4 1.2 1. ]


In [25]:
nd_array = np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [26]:
nd_array[1][2]

3.0

In [29]:
nd_array[1,2]

3.0

In [31]:
nd_array[:2, 2]

array([1., 3.])

In [32]:
nd_array[1:, 2:4]

array([[3. , 3.5],
       [5. , 5.5]])

In [33]:
nd_array[:, 2:4]

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

In [34]:
nd_array[:2]

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

Задание 7.2

In [ ]:
try:
    from Root.src.hidden import mystery
except ImportError:
    from hidden import mystery

mystery = np.array([[-13586  15203  28445 -27117  -1781 -17182 -18049]
 [ 25936 -30968  -1297  -4593   6451  15790   7181]
 [ 13348  28049  28655  -6012  21762  25397   8225]
 [ 13240   7994  32592  20149  13754  11795   -564]
 [-21725  -8681  30305  22260 -17918  12578  29943]
 [-16841 -25392 -17278  11740   5916    -47 -32037]])


# В переменную elem_5_3 сохраните элемент из 5 строки и 3 столбца:
elem_5_3 = mystery[4, 2]
# В переменную last сохраните элемент из последней строки последнего столбца
last = mystery[-1, -1]
# В переменную line_4 сохраните строку 4
line_4 = mystery[3]
# В переменную col_2 сохраните предпоследний столбец
col_2 = mystery[:, -2]
# Из строк 2-4 (включительно) получите столбцы 3-5 (включительно)
# Результат сохраните в переменную part
part = mystery[1:4, 2:5]
#  Сохраните в переменную rev последний столбец в обратном порядке
rev = mystery[::-1, -1]
# Сохраните в переменную trans транспонированный массив
trans = mystery.transpose()

СОРТИРОВКА ОДНОМЕРНЫХ МАССИВОВ

In [47]:
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)
print(arr_new)

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


In [50]:
print(arr.sort())
print(arr)

None
[ 3  4 12 12 15 23 23 45]


РАБОТА С ПРОПУЩЕННЫМИ ДАННЫМИ

In [54]:
data = np.array([4, 9, -4, 3])
roots = np.sqrt(data)
roots

C:\Users\Dmitriy\AppData\Local\Temp\ipykernel_9172\3612371969.py:2: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

In [59]:
print(type(None))
print(type(np.nan))
type(np.nan)

<class 'NoneType'>
<class 'float'>


float

In [60]:
print(None == None)
# True
print(np.nan == np.nan)
# False

True
False


In [61]:
print(None is None)
# True
print(np.nan is np.nan)
# True
print(np.nan is None)
# False

True
True
False


In [62]:
sum(roots)

nan

In [63]:
np.isnan(roots)

array([False, False,  True, False])

In [64]:
roots[np.isnan(roots)]

array([nan])

In [66]:
roots[np.isnan(roots)] = 0
roots

array([2.        , 3.        , 0.        , 1.73205081])

In [68]:
sum(roots)

6.732050807568877

In [69]:
np.isnan(np.nan)

True

In [70]:
np.nan == np.nan

False

In [71]:
np.nan is np.nan

True

Задание 7.4

In [8]:
try:
    from Root.src.hidden import mystery
except ImportError:
    from hidden import mystery

[ 12279. -26024.  28745.     nan  31244.  -2365.  -6974.  -9212.     nan
 -17722.  16132.  25933.     nan -16431.  29810.]

import numpy as np
    
#print(mystery)
# Получите булевый массив с информацией о np.nan в массиве mystery
# True - значение пропущено, False - значение не пропущено
nans_index = np.isnan(mystery)
print(nans_index)

# В переменную n_nan сохраните число пропущенных значений
n_nan = sum(nans_index)
print(n_nan)

# Заполните пропущенные значения в массиве mystery нулями
mystery[nans_index] = 0
print(mystery)


# Поменяйте тип данных в массиве mystery на int32
mystery = np.int32(mystery)
print(mystery)


# Отсортируйте значения в массиве по возрастанию и сохраните
# результат в переменную array
array = np.sort(mystery)
print(array)

# Сохраните в массив table двухмерный массив, полученный из массива array
# В нём должно быть 5 строк и 3 столбца. Причём порядок заполнения должен быть
# по столбцам! Например, 1, 2, 3, 4 -> 1    3
#                                      2    4
table = array.reshape((5, 3), order='F')
print(table)

#  Сохраните в переменную col средний столбец из table
col = table[:, 1]
print(col)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2992933973.py, line 6)

8. Модуль NumPy. Операции с векторами

In [1]:
import numpy as np
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2

array([14. , 10. , 10.6, 15.5])

In [2]:
list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
list1 + list2

[2, 4, 7, 2.5, 12, 6, 3.6, 13]

In [3]:
[x + y for x, y in zip(list1, list2)]

[14, 10, 10.6, 15.5]

In [4]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 * vec2

array([24. , 24. , 25.2, 32.5])

In [9]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6])
 
vec1 * vec2

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [6]:
vec = np.arange(5)
vec * 10
# array([ 0, 10, 20, 30, 40])
vec ** 2

array([ 0,  1,  4,  9, 16])

In [7]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
 
vec1 > vec2

array([False, False,  True, False])

In [8]:
vec = np.array([14,15,9,26,53,5,89])
vec <= 26

array([ True,  True,  True,  True, False,  True, False])

In [9]:
vec = np.array([3, 4])

length = np.sqrt(np.sum(vec ** 2))
print(length)


5.0


In [10]:
length = np.linalg.norm(vec)
print(length)

5.0


In [11]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
distance

12.206555615733702

In [12]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance

12.206555615733702

In [13]:
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1 * vec2)
scalar_product

250.0

In [14]:
scalar_product = np.dot(vec1, vec2)
scalar_product

250.0

In [15]:
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y)

0

Задание 8.4

Векторы в геометрии, которые параллельны друг другу, называются сонаправленными. На плоскости это выглядит следующим образом:
Img

Также векторы могут быть параллельны и в пространстве. На практике есть несколько способов определить сонаправленность векторов. Один из них: сумма длин сонаправленных векторов должна быть равной длине суммы двух векторов.

С помощью этого критерия найдите пару сонаправленных векторов.

In [28]:
import numpy as np
a = np.array([23, 34, 27])
b = np.array([-54, 1,  46])
c = np.array([46, 68, 54])

len_a = np.linalg.norm(a)
print(length_a)

len_b = np.linalg.norm(b)
print(length_b)

len_c = np.linalg.norm(c)
print(length_c)

print(len_a + len_b == np.linalg.norm(a+b))
print(len_a + len_c == np.linalg.norm(a+c))
print((len_b +len_c) == np.linalg.norm(b+c))

49.13247398615299
70.94363960215179
98.26494797230598
False
True
False


Задание 8.5

Найдите пару векторов, расстояние между которыми больше 100.

In [36]:
dist_ab = np.linalg.norm(a-b)
print(distance_ab)

dist_ac = np.linalg.norm(a-c)
print(dist_ac)

dist_bc = np.linalg.norm(b-c)
print(dist_bc)

85.901105930017
49.13247398615299
120.6358155772986


Задание 8.6

Найдите пару перпендикулярных векторов с помощью скалярного произведения (оно должно быть равно нулю).

In [40]:

ab = np.dot(a, b)
print(ab)

ac = np.dot(a, c)
print(ac)

bc = np.dot(b, c)
print(bc)

34
4828
68


Задание 8.7

Найдите минимальное значение в массиве mystery.

In [ ]:
[481  18 308  13 652 391  63  62 353 111 805 251  36 544 600 799 283 880
 470 599 814 507 242 650 180 860 979 298 621 197 572 976 905 427 119 905
  64 430 742 563 382 211 228 760 567 366 103 409 211 952   5 493 151 267
 517 495 375  80 341  39 560  85 490  44  17 151  42 688 648 501 437 154
  66  28 921 642 196 719 208 492 538 687 841 933 386 719 114 261 838 228
 120 508 316 476 233 902 698 471 604 172 993 790 557 129 446  64 317 997
 509 710 909 147 228 595 188 246 728 509 365 139 773 426 929 888 534 513
 666  77 299 943 985 588 137  31 385 405 980 854 327 714 318 909 803 334
 130 949 532 640 820 975 889 240 878 294 899 488 639 961 819 649 939 163
 209 879 479 573 557  25 783 332 311 425 140 678 766 492 234 316 811 447
 772 325 640 387 858 208 739 870 227 385  24 286  22 599 951 994 457  99
 238 172 549 932 412 545 713  19 785 931 684 333 630 752 191 949 200 361
 887 243 753 600 635 243 173 249 294 583 106 772 848 387 874 321 562  96
 211 561 918 868 206 745 710 869 387 600 726 179 336 806 392 612]

In [10]:
#from hidden import mystery
import numpy as np

print(mystery.min())

NameError: name 'mystery' is not defined

Задание 8.8

Найдите среднее значение массива. Ответ не округляйте.

In [1]:
print(mystery.mean())

NameError: name 'mystery' is not defined

Задание 8.9

Найдите медиану массива.

In [2]:
print(np.median(mystery))

NameError: name 'np' is not defined

Задание 8.10

Найдите стандартное отклонение значений в массиве. Ответ округлите до сотых.

In [11]:
print(round(np.std(mystery), 2))

NameError: name 'mystery' is not defined

9. Модуль NumPy. Случайные числа

In [42]:
import numpy as np
np.random.rand()

0.8037903284559802

In [44]:
np.random.rand() * 100

38.71299471785363

In [45]:
np.random.rand(5)

array([0.07644389, 0.59385935, 0.67223607, 0.10153413, 0.53211733])

In [46]:
np.random.rand(2, 3)

array([[0.98061215, 0.64160379, 0.02727382],
       [0.04710257, 0.94203606, 0.62251889]])

In [49]:
shape = (3, 4)
np.random.rand(*shape)

array([[0.05272166, 0.00476742, 0.55876779, 0.4913529 ],
       [0.77659875, 0.00992375, 0.45124999, 0.81756268],
       [0.63266207, 0.54396426, 0.85169987, 0.87667031]])

In [51]:
shape = (2, 3)
np.random.sample(shape)

array([[0.43527756, 0.68861507, 0.17659189],
       [0.42818829, 0.28377444, 0.35290326]])

In [54]:
np.random.uniform()

0.5069339505706625

In [55]:
np.random.uniform(-30, 50)

-8.824893754022902

In [56]:
np.random.uniform(0.5, 0.75, size=5)

array([0.61959729, 0.52222076, 0.5222796 , 0.56429363, 0.62608286])

In [57]:
np.random.uniform(-1000, 500, size=(2, 3))

array([[-630.86760002,  246.21980405, -550.94107035],
       [-389.87638489, -280.33594346, -252.90729071]])

In [58]:
np.random.randint(4, size=(2,3))

array([[2, 2, 3],
       [2, 0, 3]])

In [59]:
np.random.randint(6, 12, size=(3,3))

array([[ 7,  8,  9],
       [ 8,  6, 10],
       [ 7, 11,  6]])

ГЕНЕРАЦИЯ ВЫБОРОК

In [60]:
arr = np.arange(6)
print(arr)
# [0 1 2 3 4 5]
print(np.random.shuffle(arr))
# None
arr
# array([0, 5, 1, 3, 2, 4])

[0 1 2 3 4 5]
None


array([0, 2, 4, 5, 3, 1])

In [61]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
# ['The Beatles' 'Pink Floyd' 'Deep Purple' 'ACDC']
print(playlist)
# ['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']

['Pink Floyd' 'ACDC' 'Deep Purple' 'The Beatles']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


In [12]:
np.random.permutation(10)

array([0, 4, 8, 7, 1, 2, 6, 5, 3, 9])

In [64]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
 
choice = np.random.choice(workers, size=2, replace=False)
print(choice)

['Nikita' 'John']


In [14]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
#choice = np.random.choice(workers, size=10, replace=False)
#print(choice)

In [66]:
choice = np.random.choice([1,2,3,4,5,6], size=10)
print(choice)

[2 1 5 5 2 1 4 6 4 2]


SEED ГЕНЕРАТОРА ПСЕВДОСЛУЧАЙНЫХ ЧИСЕЛ

In [68]:
np.random.seed(23)
np.random.randint(10, size=(3,4))

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [69]:
np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]

[8 8 3]
[7 7 0]
[4 2 5]


ЗАДАНИЕ 9.6

Задайте seed равным 2021.

Сохраните в переменные необходимые значения.

Пожалуйста, не меняйте названия переменных и последовательность генерации случайных чисел в задании.

In [15]:
import numpy as np
np.random.seed(2021)

# В simple сохранте случайное число в диапазоне от 0 до 1
simple = np.random.rand()
print(simple)

# Сгенерируйте 120 чисел в диапазоне от -150 до 2021, сохраните их
# в переменную randoms
randoms = np.random.uniform(-150, 2021, size=120)
print(randoms)

# Получите массив из случайных целых чисел от 1 до 100 (включительно)
# из 3 строк и 2 столбцов. Сохраните результат в table
table = np.random.randint(1, 101, size=(3, 2))
print(table)


# В переменную even сохраните четные числа от 2 до 16 (включительно)
even = np.arange(2, 17, 2)
print(even)

# Перемешайте числа в even так, чтобы массив even изменился
print(np.random.shuffle(even))

# Получите из even 3 числа без повторений. Сохраните их в переменную select
select = np.random.choice(even, size=3, replace=False)
print(select)

# Получите переменную triplet, которая должна содержать перемешанные
# значения из массива select (сам select измениться не должен)
triplet = np.random.permutation(select)
print(triplet)

0.6059782788074047
[ 1.44214488e+03  1.51654277e+02  5.28813265e+02  2.01501516e+03
  1.28240517e+02  2.38594033e+02  1.48460111e+03  1.28755048e+03
  1.55273730e+03  6.03577336e+01 -2.28417401e+01  1.93936169e+03
  1.18854621e+03  3.80736459e+01  1.06852230e+03  1.18847514e+03
  1.94250320e+03  1.09681462e+03  6.55790201e+02  8.31607324e+02
  2.88216888e+02  1.08596141e+03  2.73553360e+02  1.11722142e+03
  8.84076551e+02  9.74175063e+02  1.63694713e+03  1.43966053e+03
 -7.88273550e-02  1.30919192e+03  1.24700551e+03  1.64761920e+03
  2.93903055e+02  1.19056852e+03  1.19102890e+03  5.03619976e+02
  1.74254881e+03  1.13013901e+03  1.98142287e+03  8.10086179e+02
  1.24235695e+02  9.54671885e+02  7.87407805e+02  1.83850479e+03
  1.38927296e+03  1.78361285e+03  1.12847065e+03  1.23255777e+03
  5.92935602e+02  1.63845066e+03  5.12482326e+02  5.17676863e+02
  2.87071500e+02  4.25673103e+02  1.26315547e+03  1.85668749e+02
  6.93866612e+02  1.25597031e+03  1.69165738e+03 -1.14109610e+01
  7.49

Задание 10.2

Переменная num задана следующим образом: num = "-65536". Можно ли положить её в массив чисел типа int16 без потери точности?

In [87]:
num = np.int16(-65536)
print(num)
np.iinfo(num)

0


iinfo(min=-32768, max=32767, dtype=int16)

In [6]:
#np.isnan(np.nan)
#np.isnan(elem)